# Generated by Django 5.2 on 2025-05-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='client.client'),
            preserve_default=False,
        ),
    ]
