# Generated by Django 5.2 on 2025-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_mission_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='Category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Design'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
