# Generated by Django 5.2.1 on 2025-05-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_mission_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='Category',
            new_name='category',
        ),
    ]
