# Generated by Django 5.2.1 on 2025-05-18 19:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_company_name_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='MA', max_length=2),
        ),
    ]
