# Generated by Django 5.2.1 on 2025-05-18 19:37

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_client_address_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='MA', max_length=2, null=True),
        ),
    ]
