# Generated by Django 5.2.1 on 2025-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://placehold.co/150x150', upload_to='profile_pics/'),
        ),
    ]
