# Generated by Django 5.2.1 on 2025-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_client_bio_client_email_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, default='No Bio provided'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='No Email provided', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='not provided', max_length=15),
        ),
    ]
