# Generated by Django 5.2.1 on 2025-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pfp',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
