# Generated by Django 5.2.1 on 2025-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_client_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Design'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('other', 'other')], default='other', max_length=255),
        ),
    ]
