# Generated by Django 5.2.1 on 2025-05-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
