# Generated by Django 5.2.1 on 2025-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_reviews_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='file',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
