# Generated by Django 5.2.1 on 2025-05-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_reviews_file_alter_reviews_review_file'),
        ('freelancer', '0010_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='client.client'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_reviews', to='freelancer.freelancer'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='client.mission'),
        ),
    ]
