# Generated by Django 5.2.1 on 2025-05-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_reviews_client_alter_reviews_freelancer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='client',
        ),
        migrations.AddField(
            model_name='reviews',
            name='client_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_revision_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_revisions', to='client.reviews')),
            ],
        ),
    ]
