# Generated by Django 5.2.1 on 2025-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_remove_reviews_client_reviews_client_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ai_tasks',
            field=models.TextField(blank=True),
        ),
    ]
