# Generated by Django 5.2.1 on 2025-05-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
