# Generated by Django 5.2 on 2025-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(blank=True, default='No Bio Available'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.FloatField(default=0.0, max_length=2),
        ),
    ]
