# Generated by Django 5.2.1 on 2025-05-23 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 23, 9, 24, 38, 28525, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('zh', 'Chinese (Mandarin)'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('de', 'German'), ('ja', 'Japanese'), ('ko', 'Korean'), ('it', 'Italian'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('fa', 'Persian (Farsi)'), ('sw', 'Swahili'), ('pl', 'Polish'), ('nl', 'Dutch'), ('tl', 'Filipino (Tagalog)'), ('ro', 'Romanian'), ('el', 'Greek'), ('th', 'Thai'), ('he', 'Hebrew'), ('ms', 'Malay'), ('uk', 'Ukrainian'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('id', 'Indonesian'), ('my', 'Burmese'), ('si', 'Sinhala'), ('ne', 'Nepali'), ('am', 'Amharic'), ('so', 'Somali'), ('af', 'Afrikaans'), ('is', 'Icelandic'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('ht', 'Haitian Creole'), ('eu', 'Basque'), ('ga', 'Irish (Gaelic)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
