# Generated by Django 5.2.1 on 2025-05-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
