# Generated by Django 5.2.1 on 2025-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_alter_service_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='pfp',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='No Description Available'),
        ),
    ]
