# Generated by Django 5.2.1 on 2025-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_freelancer_pfp_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/services'),
        ),
    ]
